$(document).ready(function() {
  
  $('#textarea1').hide();
  $('#select2').hide();
  $('#select3').hide();
  $('#select4').hide();
  $('#select5').hide();
  $('#select6').hide();
  $('#select7').hide();
  $('#ocultarSerial').hide();
  $('#ocultarCodigo').hide();
  $('#select8').hide();
  $('#select9').hide();
  $('#select10').hide();
  
  $('.imprimir').click(function(){
    window.print();
    return false;
  });

  $('#selectPC').click(function(){
    $('#select7').hide();
    $('#select6').hide();
    $('#select5').hide();
    $('#select4').hide();
    $('#select2').hide();
    $('#select3').hide();
    $('#textarea1').hide();
    $('#ocultarSerial').hide();
    $('#ocultarCodigo').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
  $('#selectNotebook').click(function(){
    $('#select2').show();
    $('#select5').show();
    $('#select3').hide();
    $('#select4').hide();
    $('#select6').hide();
    $('#select7').hide();
    $('#textarea1').hide();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
  $('#selectNetbook').click(function(){
    $('#select3').show();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select2').hide();
    $('#select4').hide();
    $('#textarea1').hide();
    $('#select5').show();
    $('#select6').hide();
    $('#select7').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
  $('#selectAllInOne').click(function(){
    $('#select6').show();
    $('#select7').show();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select2').hide();
    $('#select3').hide();
    $('#select4').hide();
    $('#select5').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();
    $('#textarea1').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
  $('#selectMonitor').click(function(){
    $('#select4').show();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select2').hide();
    $('#select3').hide();
    $('#select5').hide();
    $('#select6').hide();
    $('#select7').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();
    $('#textarea1').hide();

    $('#pestañaSO').hide();
    $('#pestañaOffice').hide();
    $('#pestañaDiseño').hide();
    $('#pestañaArqui').hide();
  });
  $('#selectImpresora').click(function(){
    $('#select8').show();
    $('#select9').show();
    $('#select10').show();
    $('#ocultarAccesorio').hide();
    //$('#ocultarSerial').hide();
    //$('#ocultarCodigo').hide();
    $('#select2').hide();
    $('#select3').hide();
    $('#select4').hide();
    $('#select5').hide();
    $('#select6').hide();
    $('#select7').hide();
    $('#textarea1').hide();

    $('#pestañaSO').hide();
    $('#pestañaOffice').hide();
    $('#pestañaDiseño').hide();
    $('#pestañaArqui').hide();
  });
  $('#textareaOtros').click(function(){
    $('#textarea1').show();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select2').hide();
    $('#select3').hide();  
    $('#select4').hide();
    $('#select5').hide();
    $('#select6').hide();
    $('#select7').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').hide();
    $('#pestañaOffice').hide();
    $('#pestañaDiseño').hide();
    $('#pestañaArqui').hide();
  });

  //-------------------------------------
    $('#selectPC').keypress(function(){
    $('#select7').hide();
    $('#select6').hide();
    $('#select5').hide();
    $('#select4').hide();
    $('#select2').hide();
    $('#select3').hide();
    $('#textarea1').hide();
    $('#ocultarSerial').hide();
    $('#ocultarCodigo').hide();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
  $('#selectNotebook').keypress(function(){
    $('#select2').show();
    $('#select5').show();
    $('#select3').hide();
    $('#select4').hide();
    $('#select6').hide();
    $('#select7').hide();
    $('#textarea1').hide();
    $('#ocultarSerial').show();
    $('#ocultarCodigo').show();
    $('#select8').hide();
    $('#select9').hide();
    $('#select10').hide();

    $('#pestañaSO').show();
    $('#pestañaOffice').show();
    $('#pestañaDiseño').show();
    $('#pestañaArqui').show();
  });
});